### ISSUE TITLE
How to access the response status and request params in middleware?

### ISSUE THREAD

**Issue by penguinpowernz** [strongloop/loopback-example-middleware#10]
I'm wanting to log some simple output for helping with debugging apps that use the API.  I have it showing the request and the URI but it would also be good to show the params and status code.  Like so:

For example:
```
200 GET /devices/1
  {
    id: 1
  }

404 GET /devices/999
```

I've tried putting my "spy" middleware at all levels of the `middleware.json` and dumping req but cannot find where the params or status code is populated.

Or is there a much better way to go about this?

**Comment by richardpringle** [comment]
`DEBUG=strong-remoting:*` should work!

**Comment by richardpringle** [comment]
^ @penguinpowernz

I'm going to close the issue, but please feel free to re-open if you think it's necessary. Just make sure to mention me in a comment so I can take a look right away (instead of having to wait a could months again :sweat:... sorry).

**Comment by penguinpowernz** [comment]
Oh forgot about this.. thanks.

That line did help me, but for custom logging of requests to the console I found this to be the solution:

```js
module.exports = function() {
  return function(req, res, next) {
    var u = req.url
    res.on("finish", function() {
      console.log("["+timestamp()+ "] "+res.statusCode+ " "+req.method+" "+u);
    });

    next()
  }
}
```
