### ISSUE TITLE
how to define a complex middleware parameter

### ISSUE THREAD

**Issue by jebai0521** [strongloop/loopback-example-middleware#4]
a session middleware define in server js like this

```
  app.middleware('session:before', loopback.cookieParser(app.get('cookieSecret')));
```

i define it in middleware.json like this

```
  "session:after": {
    "loopback#cookieParser": {
      "params": "app.get('cookieSecret')"
    }
  },
```

what's the right way to write *app.get('cookieSecret')* in middleware.json

**Comment by hacksparrow** [comment]
Do this:
```
  "session:after": {
    "loopback#cookieParser": {
      "params": "${cookieSecret}"
    }
  }
```
Any app variable, which can be resolved by `app.get()`, can be used within `${}`.

**Comment by hacksparrow** [comment]
@jebai0521 I hope that helps.

**Comment by richardpringle** [comment]
@jebai0521, looks like @hacksparrow solved the issue! I'm going to close it now, but if the issue persists, you can always re-open it. If you do need to re-open, mention me in a comment and I will make sure someone take a look right away.

**Comment by fabianorodrigo** [comment]
@hacksparrow / @jebai0521 , 
I've got this exception when started my loopback API: Error: Cannot resolve path "loopback/server/middleware/cookieParser"

How to solve it?

Thanks,

**Comment by asaf050** [comment]
+1

**Comment by pbalan** [comment]
+1

**Comment by richardpringle** [comment]
@pbalan, I suggest opening another issue.

Also, try to debug to see what's trying to find the cookie-parser

**Comment by pbalan** [comment]
@richardpringle I solved the issue already. Many thanks for your response.
This is what I did, just in case someone else comes looking for the answer.

```
npm install express-session --save
npm install cookie-parser --save
```

- To add these middleware, add the below code to your server/middleware.json file
```
"session:before": {
  "cookie-parser": { "params": "test secret" }
},
"session": {
  "express-session": {
    "params": {
      "secret": "other test secret",
      "saveUninitialized": true,
      "resave": true
    }
  }
}
```

**Comment by lalithenqos** [comment]
On above answer's, i see this below block for adding cookie parser in loopback middleware. I dont know what is this 'cookieSecret' variable injected in params.

```
"session:after": {
    "loopback#cookieParser": {
      "params": "${cookieSecret}"
    }
  }
```

Is cookieSecret used anywhere else ?

**Comment by ffflabs** [comment]
@lalithenqos  You'd need to define it inside your config file

```json
{
  "restApiRoot": "/api",
  "host": "0.0.0.0",
  "cookieSecret": "__THIS_IS_SO_SECRET___"
}
```

**Comment by lazzyms** [comment]
Hey, can you look into this : https://stackoverflow.com/questions/57271853/store-session-in-operation-hook-loopback
